'use strict';
(() => {
const $ = id => document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d');
const W=900,H=520, key='orbit-orchard-scores', soundKey='orbit-orchard-sound';
let scores=[],sound=false;
try {const saved=JSON.parse(localStorage.getItem(key)||'[]'); scores=Array.isArray(saved)?saved.filter(n=>Number.isFinite(n)&&n>=0).sort((a,b)=>b-a).slice(0,5):[];sound=localStorage.getItem(soundKey)==='true';}catch{}
let state='menu',score=0,level=1,lives=3,caught=0,x=W/2,objects=[],particles=[],spawn=0,invincible=0,last=0,time=0, audio;
const keys=new Set(),stars=Array.from({length:85},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.4+.3}));
function save(){try{localStorage.setItem(key,JSON.stringify(scores));}catch{}renderScores();}
function renderScores(){$('best').textContent=scores[0]||0;$('highscores').replaceChildren(...(scores.length?scores.map(n=>{const li=document.createElement('li');li.textContent=n.toLocaleString()+' points';return li;}):[Object.assign(document.createElement('li'),{textContent:'Your first adventure awaits.'})]));}
function soundLabel(){$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));}
function tone(freq){if(!sound)return;try{audio ||=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);o.start();o.stop(audio.currentTime+.17);}catch{}}
function hud(){$('score').textContent=score;$('level').textContent=level;$('lives').textContent='♥ '.repeat(lives)||'—';}
function overlay(title,copy,button){$('overlay-title').textContent=title;$('overlay-copy').textContent=copy;$('play').textContent=button;$('overlay').hidden=false;}
function start(){state='playing';score=0;level=1;lives=3;caught=0;x=W/2;objects=[];particles=[];spawn=.4;invincible=0;keys.clear();$('toast').textContent='';$('overlay').hidden=true;$('pause').disabled=false;$('pause').textContent='Pause';hud();canvas.focus();tone(440);}
function pause(){if(state==='playing'){state='paused';keys.clear();overlay('A moment of stillness.','Your stars will wait for you.','Resume exploring');$('pause').textContent='Resume';}else if(state==='paused'){state='playing';$('overlay').hidden=true;$('pause').textContent='Pause';canvas.focus();}}
function finish(){state='over';scores=[...scores,score].sort((a,b)=>b-a).slice(0,5);save();$('pause').disabled=true;overlay('A lovely little journey.',`You gathered ${score.toLocaleString()} points and reached level ${level}.`,'Explore again →');}
function burst(px,py,color){for(let i=0;i<12;i++)particles.push({x:px,y:py,vx:(Math.random()-.5)*140,vy:(Math.random()-.5)*140,life:.5,color});}
$('play').onclick=()=>state==='paused'?pause():start();$('restart').onclick=start;$('pause').onclick=pause;
$('sound').onclick=()=>{sound=!sound;soundLabel();try{localStorage.setItem(soundKey,String(sound));}catch{}tone(600);};
$('clear').onclick=()=>{scores=[];save();};
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','a','d','A','D'].includes(e.key)&&state==='playing'){e.preventDefault();keys.add(e.key.toLowerCase());}if(e.key.toLowerCase()==='p'&&!e.repeat)pause();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});
function point(e){if(state!=='playing')return;const r=canvas.getBoundingClientRect();x=Math.max(27,Math.min(W-27,(e.clientX-r.left)/r.width*W));}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);point(e);});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||e.buttons)point(e);});
function star(px,py,r,color){ctx.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI/5-Math.PI/2,rr=i%2?r*.45:r;const xx=px+Math.cos(a)*rr,yy=py+Math.sin(a)*rr;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);}ctx.closePath();ctx.fillStyle=color;ctx.fill();}
function update(dt){time+=dt;if(state!=='playing')return;if(keys.has('arrowleft')||keys.has('a'))x-=450*dt;if(keys.has('arrowright')||keys.has('d'))x+=450*dt;x=Math.max(27,Math.min(W-27,x));invincible=Math.max(0,invincible-dt);spawn-=dt;if(spawn<=0){objects.push({x:25+Math.random()*(W-50),y:-20,type:Math.random()<.7?'star':'rock',speed:Math.min(460,105+level*19),rotation:Math.random()*6});spawn=Math.max(.24,.75-level*.035);}
for(const o of objects){o.y+=o.speed*dt;o.rotation+=dt;if(Math.abs(o.x-x)<(o.type==='star'?35:32)&&Math.abs(o.y-(H-48))<23){if(o.type==='star'){o.y=H+50;score+=100;caught++;tone(660);burst(o.x,H-48,'#e6c47a');const next=1+Math.floor(caught/10);if(next>level){level=next;$('toast').textContent=`Level ${level} · A brighter, faster sky`;setTimeout(()=>{$('toast').textContent='';},2300);}hud();}else if(!invincible){o.y=H+50;lives--;invincible=1.5;burst(x,H-48,'#db8f81');tone(140);hud();if(!lives){finish();break;}}}}
objects=objects.filter(o=>o.y<H+30);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}particles=particles.filter(p=>p.life>0);}
function draw(){ctx.clearRect(0,0,W,H);const bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#112033');bg.addColorStop(1,'#17273b');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);for(const s of stars){ctx.globalAlpha=.35+.25*Math.sin(time*.6+s.x);ctx.fillStyle='#c9d8e2';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;ctx.strokeStyle='#aec5db0d';for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(W/2,H+190,450+i*110,270+i*80,0,0,Math.PI*2);ctx.stroke();}for(const o of objects){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.rotation);if(o.type==='star'){ctx.shadowColor='#e6c47a';ctx.shadowBlur=16;star(0,0,13,'#e6c47a');}else{ctx.fillStyle='#cf8378';ctx.beginPath();ctx.moveTo(-12,-8);ctx.lineTo(2,-15);ctx.lineTo(14,-2);ctx.lineTo(8,12);ctx.lineTo(-10,10);ctx.closePath();ctx.fill();ctx.strokeStyle='#efb09c';ctx.stroke();}ctx.restore();}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3);}ctx.globalAlpha=1;if(state!=='menu'){ctx.save();ctx.translate(x,H-48);ctx.globalAlpha=invincible?(.4+.6*Math.abs(Math.sin(time*15))):1;ctx.shadowColor='#99c5c3';ctx.shadowBlur=18;ctx.fillStyle='#8cbebd';ctx.beginPath();ctx.moveTo(-27,-7);ctx.quadraticCurveTo(0,25,27,-7);ctx.lineTo(18,11);ctx.quadraticCurveTo(0,29,-18,11);ctx.closePath();ctx.fill();ctx.strokeStyle='#def5e6';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-27,-7);ctx.quadraticCurveTo(0,2,27,-7);ctx.stroke();star(0,7,5,'#f4deb0');ctx.restore();}}
function frame(t){const dt=Math.min((t-last)/1000||0,.04);last=t;update(dt);draw();requestAnimationFrame(frame);}renderScores();soundLabel();hud();requestAnimationFrame(frame);
})();
